# Generated by Django 5.1.15 on 2026-10-10 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('pathway_stage', models.CharField(choices=[('stage-01', 'Stage 01: Clinical Navigation (TCF PATHWAY)'), ('stage-02', 'Stage 02: Integrative Care (TCF ADVOCACY)'), ('stage-03', 'Stage 03: Moderated Spaces (TCF CONNECTION)'), ('stage-04', 'Stage 04: Survivorship Plans (TCF VOICES)'), ('general-flagship', 'General Flagship Campaign')], default='stage-01', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('banner_image', models.URLField(blank=True, max_length=500, null=True)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active / Live'), ('upcoming', 'Upcoming'), ('completed', 'Completed / Archived')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('legacy_sanity_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pathway_stage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='image', max_length=50)),
                ('legacy_sanity_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='TCF 001', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('embed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('legacy_sanity_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_title', models.CharField(default='The Carcino Foundation', max_length=255)),
                ('tagline', models.CharField(default='Turning Knowledge Into Action in Oncology', max_length=255)),
                ('revalidation_secret', models.CharField(default='carcino-cms-revalidation-secret-2026', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='legacy_sanity_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='legacy_sanity_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='legacy_sanity_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
